permalink:  /posts/:title.html
exclude: [ Makefile, README.md, atom.xml ]
safe: false
highlighter: pygments
tag_dir: /tags
tag_title_prefix: "Jonathan Perkin &raquo; "
tag_title_suffix: ""
url: www-test.perkin.org.uk
